spring.application.name=shortlink-service
server.port=${PORT:8080}
spring.profiles.default=mysql
spring.jpa.open-in-view=false
spring.data.redis.repositories.enabled=false
app.base-url=${APP_BASE_URL:http://localhost:${server.port}}
app.cache.enabled=${CACHE_ENABLED:true}
app.cache.ttl-seconds=${CACHE_TTL_SECONDS:3600}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USERNAME:}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}
spring.data.redis.connect-timeout=1s
spring.data.redis.timeout=1s
springdoc.api-docs.version=OPENAPI_3_0
springdoc.override-with-generic-response=false
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.persist-authorization=false
